### PR TITLE
Resolve longstanding deep_merge! bug

### LINKED ISSUE #55: Two errors in custom merge
Bad check at:
https://github.com/projectblacklight/blacklight_advanced_search/blob/master/lib/blacklight_advanced_search.rb#L30

```ruby
if new_value.respond_to?(:blank) && new.blank?
```
`:blank` vs. `:blank?` and `new_value` vs. `new`

Looks like the new/new_value error was introduced here: https://github.com/projectblacklight/blacklight_advanced_search/commit/6d3b49ace134b488c92b63e31fd622a82a5951cc#diff-4961a18d7c088f36dc4f670c73ae74a6R30

And the other in 2011 or before (so far back, I don’t care anymore).  Got test coverage?

### PR DESCRIPTION
**Pull request by atz**
Fixes #55.

Use mainline Rails `deep_merge` with a block.

Massively more robust testing, including running the deep_merge! tests
with HashWithIndifferentAccess objects to allay concerns about that class'
incompatibility.

Added docs.

### CODE REVIEW

File: lib/blacklight_advanced_search.rb [hunk 1]
```diff
@@ -12,37 +12,37 @@ module BlacklightAdvancedSearch
...
+  # - will NOT merge (non-FalseClass) blank values
+  # - WILL deduplicate values from arrays after merging them
+  #
+  # @param [Hash|HashWithIndifferentAccess] source_hash
+  # @param [Hash|HashWithIndifferentAccess] new_hash
+  # @return [Hash] the deeply merged hash
+  # @see Rails #deep_merge http://apidock.com/rails/v4.2.1/Hash/deep_merge
+  # @example new_hash = BlacklightAdvancedSearch.deep_merge(h1, h2)
+  def self.deep_merge(source_hash, new_hash)
+    source_hash.deep_merge(new_hash) { |x, y, z| merge_conflict_resolution(x, y, z) }
```
Comment (cbeer) [inline lib/blacklight_advanced_search.rb]: Could we please either use meaningful names for these arguments, or use an implicit style without names (either e.g. `source_hash.deep_merge(new_hash, &method(:merge_conflict_resolution))`?

Comment (atz) [inline lib/blacklight_advanced_search.rb]: Yeah, sure.  Indirection has a minor performance penalty, however.

File: lib/blacklight_advanced_search.rb [hunk 2]
```diff
@@ -12,37 +12,37 @@ module BlacklightAdvancedSearch
...
-          old
-        else
-          new_value
-        end
+  # the arguments are set by what the Rails Hash.deep_merge supplies the block
+  def self.merge_conflict_resolution(_key, old, new_value)
+    return old if new_value.nil?
+    return old if new_value.respond_to?(:blank?) && new_value.blank? && !new_value.is_a?(FalseClass)
+    return old | new_value if old.is_a?(Array) && new_value.is_a?(Array)
+    if old.is_a?(Hash) && new_value.is_a?(Hash)
```
Comment (cbeer) [inline lib/blacklight_advanced_search.rb]: Do we need to handle to this case now that we're actually using `#deep_merge`?

Comment (atz) [inline lib/blacklight_advanced_search.rb]: Yes, because of the recursion.

File: lib/blacklight_advanced_search.rb [hunk 3]
```diff
@@ -12,37 +12,37 @@ module BlacklightAdvancedSearch
...
+    source_hash.deep_merge(new_hash) { |x, y, z| merge_conflict_resolution(x, y, z) }
+  end
 
-    new_hash.each_pair do |key, new_value|
-      old = source_hash.fetch(key, nil)
+  # this one side-effects the first param
+  # @see #deep_merge
+  # @deprecated use `new_hash = BlacklightAdvancedSearch.deep_merge(h1, h2)` instead
+  def self.deep_merge!(source_hash, new_hash)
+    source_hash.deep_merge!(new_hash) { |x, y, z| merge_conflict_resolution(x, y, z) }
```
Comment (cbeer) [inline lib/blacklight_advanced_search.rb]: Can we issue a proper deprecation warning? I'm fine with either pulling in `deprecation` or being lazy and just using `ActiveSupport::Deprecation.warn` directly.

File: lib/blacklight_advanced_search.rb (hunk 2 above)
Comment (cbeer) [inline lib/blacklight_advanced_search.rb]: I thought they'd handle that upstream for us.

Comment (cbeer) [inline lib/blacklight_advanced_search.rb]: Adding an exception in there suggests that condition is not used, and confirmed upstream: https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/hash/deep_merge.rb#L26

Comment (atz) [inline lib/blacklight_advanced_search.rb]: Or, you are saying that Rails `deep_merge` will not trigger a collision to evaluate on two hash values.  Lemme test that...

Comment (atz) [inline lib/blacklight_advanced_search.rb]: OK, that seems true.  
```ruby
x={a:{alpha:5, anchor:6}}
 => {:a=>{:alpha=>5, :anchor=>6}} 
y={a:{beta:4,banter:6}}
 => {:a=>{:beta=>4, :banter=>6}} 
x.deep_merge(y)
 => {:a=>{:alpha=>5, :anchor=>6, :beta=>4, :banter=>6}} 
x.deep_merge(y) {|q,r,s| puts "q" }
 => {:a=>{:alpha=>5, :anchor=>6, :beta=>4, :banter=>6}} 
```

Will pull that case.
